apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: prepare-{{ .Values.name }}
            image: alpine/git:2.36.3 
            command: ["git", "clone", {{ .Values.job.source_git }}, "/spaceone/jobs"]
            volumeMounts:
            - name: share
              mountPath: /spaceone
          containers:
          - name: {{ .Values.name }}
            image: {{ .Values.image.name }}:{{ .Values.image.version }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            command: ["spacectl", "apply", "/spaceone/jobs/{{ .Values.job.name }}.yaml"]
            lifecycle:
              postStart:
                exec:
                  command: ["sh", "-c", "pip3", "install", "--pre", "--upgrade", "spaceone-core", "spaceone-api"]
            volumeMounts:
            - name: share
              mountPath: /spaceone
            - name: spacectl
              mountPath: /root/.spaceone/environment.yml
              subPath: environment.yml
              readOnly: true
            - name: spacectl
              mountPath: /root/.spaceone/environments/default.yml
              subPath: default.yml
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: share
            emptyDir: {}
          - name: spacectl
            configMap:
              name: spacectl-config
